name: yandex_mapkit_example
description: Demonstrates how to use the yandex_mapkit plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  permission_handler: ^10.4.0
  yandex_mapkit:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  assets:
    - lib/assets/user.png
    - lib/assets/cluster.png
    - lib/assets/place.png
    - lib/assets/arrow.png
    - lib/assets/route_start.png
    - lib/assets/route_end.png
    - lib/assets/nigger.png
  uses-material-design: true
