// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoDHoQZJaevVGRiqMHoMk9hsJAxNA929o',
    appId: '1:217188557877:web:99d536a0ff63f3e51e7d7c',
    messagingSenderId: '217188557877',
    projectId: 'flaggcg-7d756',
    authDomain: 'flaggcg-7d756.firebaseapp.com',
    storageBucket: 'flaggcg-7d756.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6SIvV2HF3HfqcPWwdLpBrN-9e5JZMOgg',
    appId: '1:217188557877:android:ee30bca1eb491f351e7d7c',
    messagingSenderId: '217188557877',
    projectId: 'flaggcg-7d756',
    storageBucket: 'flaggcg-7d756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-EPu_ui4QW-B-VKTqglgwXH6Wo6pIIg',
    appId: '1:217188557877:ios:0e911cf76ed700691e7d7c',
    messagingSenderId: '217188557877',
    projectId: 'flaggcg-7d756',
    storageBucket: 'flaggcg-7d756.appspot.com',
    iosBundleId: 'com.example.flaggCg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3-EPu_ui4QW-B-VKTqglgwXH6Wo6pIIg',
    appId: '1:217188557877:ios:322a94a7d74e814a1e7d7c',
    messagingSenderId: '217188557877',
    projectId: 'flaggcg-7d756',
    storageBucket: 'flaggcg-7d756.appspot.com',
    iosBundleId: 'com.example.flaggCg.RunnerTests',
  );
}
